### ISSUE TITLE
Both features did not work?

### ISSUE THREAD

**Issue by stefaliu** [Phanx/AnyFavoriteMount#1]
I happened to know this addon has implemented all the 3 features I was looking for, so tried it out immediately (with the latest 6.0.3.10 version from curse). The results did not look good, unfortunately:

1) Character-specific mount options: while your addon may have supported it, another addon I was using works nicely anyway.

2) Class-specific mount being able to set as favorite: your addon did turn on the option, but for reasons I don't know, such mount (e.g. Paladin's Charger) was still not able to summon up with the button -- the button turned grey too.

3) Those apparently flying mounts (e.g. carpets, cloud, etc.) are not allowed to summon as ground mounts: it is the additional feature your addon claimed to support too, but those clumsy flying mounts are still summoned as ground mounts, and the weird thing was, even the flying mounts that were not previously summoned as ground mounts with the built-in mechanism (e.g. Blue Drake) were also summoned as ground mounts now, with your addon.

Could you please help to take a look at the issues? I really hope that one single addon could provide all I (and I believe many other people) needed with the built-in mount mechanism.

Thanks!

**Comment by Phanx** [comment]
1. AFM only saves "special" mount favorites per-character. Other mounts as favorites remain saved by Blizzard on an account-wide basis. I have no plans to change that.
2. I don't have a paladin so I have no way to test that directly, but warlock mounts are working just fine for me, so you'll have to be more specific -- what button turned gray? (AFM doesn't provide any button.) Where were you located? Which zone/continent were you in? Which riding skills do you have trained? Which mounts do you have set as favorites?
3. You can see a list of flying mounts that are allowed in non-flying areas in Addon.lua [here](https://github.com/Phanx/AnyFavoriteMount/blob/master/Addon.lua#L73), but that list doesn't include any of the mounts you mentioned. Other than that list, flying mounts are only summoned in ground areas if you don't have any ground mounts set as favorites. Again, you've not given me any actual information to go on, or any specific scenario I can try to reproduce some problem, so all I can reall tell you is that it's working fine for me.

**Comment by stefaliu** [comment]
Hi Phanx,

Thanks for the quick reply. 

I just went through the scenarios again, and hope the test case and results below could help you figure out the causes:

---

Characters: Paladin / Warlock / Death Knight
Zone: any ground-mount only zones, e.g. Garrison, any WoD wild zone, or old world zones that the toon has not bought the flying skill book yet, etc.

Pre-conditions: 
No any favorite mount is selected --> The "Summon Random Favorite Mount" (short for SRFM next) button is gray in the toolbar.

Steps:
1) Open the mount tab --> The class-specific mount for the character ("Charger" for Paladin, "Dreadsteed" and "Felsteed" for Warlock, "Acherus Death Charger" for Death Knight) could be set as favorite. ( I will take Warlock as example next)
2) Set "Dreadsteed" as favorite mount --> The SRFM button is still gray.
3) Press the SRFM button many times --> It said "You have no valid favorite mount", and nothing else happened.
4) Set an apparent flying mount (e.g. "Albino Drake") as the 2nd favorite mount --> The SRFM button is white now.
5) Press the SRFM button many times --> "Albino Drake" was always summoned up.
6) Set an apparent ground mount (e.g. "Amani Battle Bear") as the 3rd favorite mount
7) Press the SRFM button many times --> "Amani Battle Bear" was always summoned up.
8) Set a preferably flying mount (e.g. "Red Flying Cloud", or any of the 3 carpets) as the 4th favorite mount
9) Press the SRFM button many times --> "Amani Battle Bear" and "Red Flying Cloud" were randomly summoned up.

Screenshots:
(at step 3)
![warlock-mount-small](https://cloud.githubusercontent.com/assets/10769094/5973391/a7578f2c-a8a2-11e4-9029-39bdc10b4d16.png)

(at step 9)
![warlock-mounts-small](https://cloud.githubusercontent.com/assets/10769094/5973317/d6c05aa6-a8a1-11e4-8137-f64cfaf7236b.png)

---

Speculations:
1) The class-specific mount is selectable with your addon, but still does not pass the built-in checking for summoning?
2) Some preferably flying mounts (e.g. "Red Flying Cloud", or any of the 3 carpets) are still taken as "ground + flying" mounts, and hence are still summonable in a ground mount only zone.

AFM is the only active mount-related addon during my test. I don't know how to generate a list of all my active addons though, or I would have attached here in case you need it for your investigation.

Thanks.

**Comment by Phanx** [comment]
How to get a list of your addons: http://phanx.net/addons/tutorials/list

Re: 1 & 2 -- I admit I have never used the "Summon Random" button on the mount journal, but looking at the default UI code for it, I don't see how there should be any problem:

Button defined here:
http://www.townlong-yak.com/framexml/19116/Blizzard_PetJournal/Blizzard_PetJournal.xml#969

OnClick script set here:
http://www.townlong-yak.com/framexml/19116/Blizzard_PetJournal/Blizzard_PetJournal.xml#1005

Defined here:
http://www.townlong-yak.com/framexml/19116/Blizzard_PetJournal/Blizzard_PetJournal.lua#2291

Calls this function:
http://www.townlong-yak.com/framexml/19116/Blizzard_PetJournal/Blizzard_PetJournal.lua#1741

Which calls the C_MountJournal.Summon function that AFM replaces.

I'll try your test cases later when I'm at home; thanks for the detailed steps!

**Comment by stefaliu** [comment]
Hi Phanx,

Thanks for the information. Here is the addon list (most were active except a few, e.g. Armory, most CT plugins):

!BugGrabber
_NPCScan
_NPCScan.AutoAdd
_NPCScan.Overlay
AckisRecipeList
ACP
AHShowBid
Align
Aloft
AloftOptions
Altoholic
Altoholic_Achievements
Altoholic_Agenda
Altoholic_Characters
Altoholic_Grids
Altoholic_Guild
Altoholic_Search
Altoholic_Summary
AnyFavoriteMount
Armory
ArmoryGuildBank
AshranBuddy
AshranHelper
Atlas
Atlas_Arena
Atlas_Battlegrounds
Atlas_BurningCrusade
Atlas_Cataclysm
Atlas_ClassicWoW
Atlas_DungeonLocs
Atlas_MistsofPandaria
Atlas_OutdoorRaids
Atlas_Scenarios
Atlas_Transportation
Atlas_WorldEvents
Atlas_WrathoftheLichKing
AtlasLoot
AtlasLoot_BurningCrusade
AtlasLoot_Cataclysm
AtlasLoot_Classic
AtlasLoot_Collections
AtlasLoot_Crafting
AtlasLoot_Factions
AtlasLoot_MistsofPandaria
AtlasLoot_Options
AtlasLoot_PvP
AtlasLoot_WarlordsofDraenor
AtlasLoot_WorldEvents
AtlasLoot_WrathoftheLichKing
Auctionator
BadBoy
BagBrother
Bagnon
Bagnon_Config
Bagnon_GuildBank
Bagnon_VoidStorage
BaudMark
Blizzard_AchievementUI
Blizzard_ArchaeologyUI
Blizzard_ArenaUI
Blizzard_AuctionUI
Blizzard_AuthChallengeUI
Blizzard_BarbershopUI
Blizzard_BattlefieldMinimap
Blizzard_BindingUI
Blizzard_BlackMarketUI
Blizzard_Calendar
Blizzard_ChallengesUI
Blizzard_ClientSavedVariables
Blizzard_CombatLog
Blizzard_CombatText
Blizzard_CompactRaidFrames
Blizzard_CUFProfiles
Blizzard_DebugTools
Blizzard_EncounterJournal
Blizzard_GarrisonUI
Blizzard_GlyphUI
Blizzard_GMChatUI
Blizzard_GMSurveyUI
Blizzard_GuildBankUI
Blizzard_GuildControlUI
Blizzard_GuildUI
Blizzard_InspectUI
Blizzard_ItemAlterationUI
Blizzard_ItemSocketingUI
Blizzard_ItemUpgradeUI
Blizzard_LookingForGuildUI
Blizzard_MacroUI
Blizzard_MovePad
Blizzard_ObjectiveTracker
Blizzard_PetBattleUI
Blizzard_PetJournal
Blizzard_PVPUI
Blizzard_QuestChoice
Blizzard_RaidUI
Blizzard_StoreUI
Blizzard_TalentUI
Blizzard_TimeManager
Blizzard_TokenUI
Blizzard_TradeSkillUI
Blizzard_TrainerUI
Blizzard_Tutorial
Blizzard_VoidStorageUI
Buffet
BugSack
ClassTimer
Collectinator
ComboPointsRedux
ComboPointsRedux_Options
Combuctor
Combuctor_Config
Combuctor_Scrap
Combuctor_Sets
CT_BarMod
CT_BottomBar
CT_BuffMod
CT_Core
CT_ExpenseHistory
CT_Library
CT_MailMod
CT_MapMod
CT_PartyBuffs
CT_RaidAssist
CT_RaidAssist_MTPlayers
CT_Timer
CT_UnitFrames
CT_Viewport
CurrencySorter
DailyGrind
DataStore
DataStore_Achievements
DataStore_Agenda
DataStore_Auctions
DataStore_Characters
DataStore_Containers
DataStore_Crafts
DataStore_Currencies
DataStore_Inventory
DataStore_Mails
DataStore_Pets
DataStore_Quests
DataStore_Reputations
DataStore_Spells
DataStore_Stats
DataStore_Talents
DBM-AQ20
DBM-AQ40
DBM-BaradinHold
DBM-BastionTwilight
DBM-BlackrockFoundry
DBM-BlackTemple
DBM-BlackwingDescent
DBM-Brawlers
DBM-BWL
DBM-ChamberOfAspects
DBM-Coliseum
DBM-Core
DBM-DefaultSkin
DBM-DMF
DBM-Draenor
DBM-DragonSoul
DBM-EyeOfEternity
DBM-Firelands
DBM-GUI
DBM-HeartofFear
DBM-Highmaul
DBM-Hyjal
DBM-Icecrown
DBM-Karazhan
DBM-MC
DBM-MogushanVaults
DBM-Naxx
DBM-Onyxia
DBM-Outlands
DBM-Pandaria
DBM-Party-BC
DBM-Party-Cataclysm
DBM-Party-MoP
DBM-Party-WoD
DBM-Party-WotLK
DBM-PvP
DBM-Scenario-MoP
DBM-Serpentshrine
DBM-SiegeOfOrgrimmarV2
DBM-StatusBarTimers
DBM-Sunwell
DBM-TerraceofEndlessSpring
DBM-TheEye
DBM-ThroneFourWinds
DBM-ThroneofThunder
DBM-Ulduar
DBM-VoA
DBM-WorldEvents
Decursive
FishingBuddy
GatherMate2
GatherMate2_Data
Grid
GridManaBars
GridStatusDungeonRole
GridStatusRole
HandyNotes
HandyNotes_DraenorTreasures
HideCleanUpBagsButton
JPack
JPack_Broker
JPack_Ex
MagicRunes
MagicRunes_IconDisplay
MagicRunes_RuneBars
MasterPlan
MinimapButtonFrame
MinimapButtonFrame_SkinPack
Oilvl
OmniCC
OmniCC_Config
oRA3
Outfitter
Overachiever
Overachiever_Tabs
Overachiever_Trade
Paste
PetTracker
PetTracker_Breeds
PetTracker_Config
PetTracker_Journal
PetTracker_Switcher
PetTracker_Upgrades
Postal
Prat-3.0
Prat-3.0_HighCPUUsageModules
Prat-3.0_Libraries
Quartz
Quartz_Procs
QuestItemBar
RaidAchieveFilter
RaidAchievement
RaidAchievement_CataHeroics
RaidAchievement_CataRaids
RaidAchievement_Icecrown
RaidAchievement_Naxxramas
RaidAchievement_OldModules
RaidAchievement_PandaHeroics
RaidAchievement_PandaRaids
RaidAchievement_PandaScenarios
RaidAchievement_Ulduar
RaidAchievement_WoDHeroics
RaidAchievement_WoDRaids
RaidAchievement_WotlkHeroics
Rarity
Rarity_Options
RSA
RSA_DeathKnight
RSA_Druid
RSA_Hunter
RSA_Mage
RSA_Monk
RSA_Options
RSA_Paladin
RSA_Priest
RSA_Reminders
RSA_Rogue
RSA_Shaman
RSA_Warlock
RSA_Warrior
Scrap
Scrap_Merchant
Scrap_Options
Scrap_Spotlight
Scrap_Visualizer
Skada
SpamThrottle
tekability
tekKompare
TipTac
TipTacItemRef
TipTacOptions
TipTacTalents
Titan
TitanBag
TitanClock
TitanGold
TitanLocation
TitanLootType
TitanPerformance
TitanRepair
TitanSpec
TitanVolume
TitanXP
TomTom
TotemTimers
TrinketMenu
tullaRange
tullaRange_Config
VendorBait
WorldBossStatus
XLoot
XLoot_Frame
XLoot_Group
XLoot_Master
XLoot_Monitor
XLoot_Options

And just to clarify that, I have put the "Summon Random" button in the right action bar (the second to the bottom), and have bound a key to it. Each time, I was actually pressing the bound key instead, although I assume it should have the same effect as pressing the "Summon Random" button in the mount journal anyway.

Thanks again.

**Comment by Phanx** [comment]
> I have put the "Summon Random" button in the right action bar (the second to the bottom), and have bound a key to it. Each time, I was actually pressing the bound key instead, although I assume it should have the same effect as pressing the "Summon Random" button in the mount journal anyway.

This assumption would likely be incorrect, as the default action buttons use "action" commands internally rather than actual macro commands (like "/click this button" or "/cast this spell"). I'll look into it further as soon as I have time, but can you try clicking the actual button in the mount journal instead? If that works, then most likely I will just modify the button to create a macro when dragging it onto an action bar instead, since it's likely the related "action" command can't be overridden.

**Comment by stefaliu** [comment]
Dear Phanx,

I never know the underlying logic between clicking a default button and clicking its shortcut in the tool bar is different. But after quite some tests again just now, it looks like that you are correct -- the incorrect behaviors I described actually happened with clicking the button in the tool bar, and when I clicked the button in the mount journal, the behaviors looked all right so far. So once you override the button the way you mentioned, users like me using buttons in the tool bar should be able to see the expected behaviors again.

The only left feature I wish for the built-in mount mechanism is that, each character could have his/her own favorite mount. I don't really like the idea that big tauren and small goblin always summon the same mount of same size and same look, which is boring too, isn't it? Is there any possibility that you could integrate that feature in your addon too? Please .... =P

Btw, while I felt that your name sounds a bit familiar in submitting the issue, I just realized the other day that you were the active author of Grid and some other addons that I had been using. Thanks for all the efforts and convenience to help us play this game in a more enjoyable way!

Cheers.
