### ISSUE TITLE
Doesn't work directly from action buttons

### ISSUE THREAD

**Issue by Phanx** [Phanx/AnyFavoriteMount#2]
Need to investigate exactly what happens when the user drags the "Summon Random Mount" button from the mount journal to an action button and feed that into the custom logic if possible, or overwrite the button's drag script to create/pickup a macro instead if not.

(from #1)

**Comment by Funsponge** [comment]
I got around this by making a macro with:

/run C_MountJournal.Summon(0)

Might want to add that into the description on the site.

**Comment by Phanx** [comment]
Fixed
